name: Build And Upload Extension Zip Via Artifact

on:
  push:
    branches: [ main ]
    paths:
      - 'savvy-extension/**'
  pull_request:

jobs:
  build:
    defaults:
      run:
        working-directory: savvy-extension

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: 'savvy-extension/package.json'
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'savvy-extension/.nvmrc'
          cache: pnpm

      - run: pnpm install --frozen-lockfile --prefer-offline

      - run: pnpm build

      - uses: actions/upload-artifact@v4
        with:
          path: dist/*
