name: Run E2E Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'savvy-extension/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'savvy-extension/**'

jobs:
  chrome:
    defaults:
      run:
        working-directory: savvy-extension
    name: E2E tests for Chrome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: savvy-extension/package.json
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: pnpm
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm e2e
