name: Lint Check

on:
  push:
    branches: [ main ]
    paths:
      - 'savvy-extension/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'savvy-extension/**'

jobs:
  eslint:
    defaults:
      run:
        working-directory: savvy-extension

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: 'savvy-extension/package.json'
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'savvy-extension/.nvmrc'
          cache-dependency-path: 'savvy-extension/pnpm-lock.yaml'
          cache: pnpm

      - run: pnpm install --frozen-lockfile --prefer-offline

      - run: pnpm lint
